stages:
  - unittest
  - testpypi
  - pypi

default:
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  before_script:
    - python -m venv ./venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install pip-tools
    - pip-sync requirements.txt dev-requirements.txt

Unit Tests:
  stage: unittest
  script:
    - python -m pytest tests --junitxml=report.xml
  artifacts:
    reports:
      junit:
        - report.xml


Test PyPI Deployment:
  stage: testpypi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "PACKAGE_VERSION=$(grep version= setup.py | cut -d= -f2 | sed "s/[\',]//g")" >> $GITLAB_ENV
    - python setup.py sdist
    - TWINE_PASSWORD=$PYPI_TEST_API_TOKEN TWINE_USERNAME=__token__ python3 -m twine upload --repository testpypi dist/*
  artifacts:
    paths:
      - dist/
  environment:
    name: pypi
    url: https://test.pypi.org/project/hca-ingest/${PACKAGE_VERSION}


PyPI Deployment:
  stage: pypi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - echo "PACKAGE_VERSION=$(grep version= setup.py | cut -d= -f2 | sed "s/[\',]//g")" >> $GITLAB_ENV
    - TWINE_PASSWORD=$PYPI_API_TOKEN TWINE_USERNAME=__token__ python3 -m twine upload dist/*
  environment:
    name: pypi
    url: https://pypi.org/project/hca-ingest/${PACKAGE_VERSION}

