Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  script:
    - pip install --upgrade pip
    - pip install pip-tools
    - pip-sync requirements.txt dev-requirements.txt
    - python -m unittest
