workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  before_script:
    - python -m venv ./venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install pip-tools
    - pip-sync requirements.txt dev-requirements.txt
  script:
    - python -m unittest
